name: Build Windows Executable

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: windows-latest

    steps:
    - uses: actions/checkout@v4

    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: '3.10'

    - name: Install dependencies
      run: |
        pip install pyinstaller

    - name: Run PyInstaller
      run: |
        pyinstaller --onefile --clean `
        --distpath windows_build `
        --icon "icon.png" `
        --add-data "Omar2/presplash.png:." `
        "in.py"
        
    - name: Upload executable
      uses: actions/upload-artifact@v4
      with:
        name: your-app-windows-exe
        path: windows_build/in.exe
