name: Build Executables

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build-windows:
    runs-on: windows-latest
    steps:
    - uses: actions/checkout@v4

    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: '3.10'

    - name: Install dependencies
      run: |
        pip install pyinstaller

    - name: Run PyInstaller
      run: |
        pyinstaller --onefile --clean `
        --distpath windows_build `
        "in.py"
        
    - name: Upload Windows executable
      uses: actions/upload-artifact@v4
      with:
        name: your-app-windows-exe
        path: windows_build/in.exe

  build-macos:
    runs-on: macos-latest
    steps:
    - uses: actions/checkout@v4

    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: '3.10'

    - name: Install dependencies
      run: |
        pip install pyinstaller

    - name: Run PyInstaller
      run: |
        pyinstaller --onefile --clean \
        --distpath macos_build \
        "in.py"

    - name: Upload macOS executable
      uses: actions/upload-artifact@v4
      with:
        name: your-app-macos-exe
        path: macos_build/in
